[theme]
base="light"
primaryColor="#5be8e6"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font = "sans serif"
headingFont = "sans serif"
codeFont = "monospace"

# [theme.sidebar]
# font = "sans serif"
# headingFont = "sans serif"
# codeFont = "monospace"
